---
title: "Old Faithful Eruptions"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: scroll
    runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
data(faithful)
```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 10)

sliderInput("bw_adjust", label = "Ajuste del ancho de banda:",
            min = 0.2, max = 2, value = 1, step = 0.2)
```

Column
-----------------------------------------------------------------------

### DURACION DE LA ERUPCION DEL GEYSER

```{r}
renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duracion en minutos", ylab= "Densidad", main = "Duracion de la erupcion del geyser", col= "blue")
  abline(h = 0.5, col = "black")
  abline(v = mean(faithful$eruptions), col = "red")
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "orange")
})
```

### PLOT DE ERUPTIONS

```{r}
{   
    plot(faithful$eruptions~faithful$waiting, xlab = "tiempo de espera entre erupciones", ylab = "erupciones")
    lines(faithful$eruptions)
}
```